version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - inamedparam
    - interfacebloat
    - lll
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - revive
    - tagalign
    - testableexamples
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wsl
  disable:
    - depguard
    - funlen
    - gochecknoinits
    - godot
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
