name: Lint OpenAPI Spec

on:
  push:
    paths:
      - '*.yaml'
      - '*.yml'
      - 'openapi/**'
  pull_request:
    paths:
      - '*.yaml'
      - '*.yml'
      - 'openapi/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint OpenAPI specification
        uses: stoplightio/spectral-action@v0.8.3
        with:
          file: ./openapi-spec.yaml
