name: openapi-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  openapi:
    name: lint openapi spec
    runs-on: ubuntu-latest
    steps:
      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: openapi-spec.yaml
